import { UniqueEntityId } from "@/core/entities/unique-entity-id";
import { QuoteItem, QuoteItemKind, MaterialCalcMode } from "@/domain/enterprise/entities/quote-item";
import { DiscountType } from "@/domain/enterprise/entities/quote";
import { ProfileType } from "@/domain/enterprise/entities/profile";
import { Prisma, QuoteItem as PrismaQuoteItem } from "@prisma/client";

export class PrismaQuoteItemMapper {
  static toDomain(raw: PrismaQuoteItem): QuoteItem {
    return QuoteItem.create(
      {
        quoteId: new UniqueEntityId(raw.quoteId),
        partNumber: raw.partNumber,
        itemKind: raw.itemKind as QuoteItemKind,
        sheetId: raw.sheetId ? new UniqueEntityId(raw.sheetId) : null,
        profileId: raw.profileId ? new UniqueEntityId(raw.profileId) : null,
        materialName: raw.materialName,
        thickness: raw.thickness,
        sheetWidth: raw.sheetWidth,
        sheetHeight: raw.sheetHeight,
        profileType: raw.profileType as ProfileType | null,
        profileLength: raw.profileLength,
        profileDimensions: raw.profileDimensions,
        baseMaterialPrice: raw.baseMaterialPrice,
        isManualPrice: raw.isManualPrice,
        isFullMaterial: raw.isFullMaterial,
        materialCalcMode: raw.materialCalcMode as MaterialCalcMode,
        sheetCount: raw.sheetCount,
        hasPartialLastSheet: raw.hasPartialLastSheet,
        partialSheetWidth: raw.partialSheetWidth,
        partialSheetHeight: raw.partialSheetHeight,
        chargeFullLastSheet: raw.chargeFullLastSheet,
        computedSheetUnits: raw.computedSheetUnits,
        profileBarCount: raw.profileBarCount,
        hasPartialLastProfileBar: raw.hasPartialLastProfileBar,
        partialProfileLength: raw.partialProfileLength,
        chargeFullLastProfileBar: raw.chargeFullLastProfileBar,
        computedProfileBarUnits: raw.computedProfileBarUnits,
        scrapNotes: raw.scrapNotes,
        isMaterialProvidedByClient: raw.isMaterialProvidedByClient,
        cuttingGasId: new UniqueEntityId(raw.cuttingGasId),
        cuttingTimeMinutes: raw.cuttingTimeMinutes,
        chargeMinimumCutting: raw.chargeMinimumCutting,
        cutWidth: raw.cutWidth,
        cutHeight: raw.cutHeight,
        cutLength: raw.cutLength,
        usagePercentage: raw.usagePercentage,
        setupRateId: raw.setupRateId ? new UniqueEntityId(raw.setupRateId) : null,
        setupTimeMinutes: raw.setupTimeMinutes,
        setupPricePerHour: raw.setupPricePerHour,
        finishingDescription: raw.finishingDescription,
        finishingPrice: raw.finishingPrice,
        materialCost: raw.materialCost,
        cuttingCost: raw.cuttingCost,
        setupCost: raw.setupCost,
        servicesCost: raw.servicesCost,
        subtotalItemCost: raw.subtotalItemCost,
        discountType: raw.discountType as DiscountType | null,
        discountValue: raw.discountValue,
        discountAmount: raw.discountAmount,
        totalItemCost: raw.totalItemCost,
        createdAt: raw.createdAt,
      },
      new UniqueEntityId(raw.id),
    )
  }

  static toPrisma(item: QuoteItem): Prisma.QuoteItemUncheckedCreateInput {
    return {
      id: item.id.toString(),
      quoteId: item.quoteId.toString(),
      partNumber: item.partNumber,
      itemKind: item.itemKind,
      sheetId: item.sheetId?.toString() ?? null,
      profileId: item.profileId?.toString() ?? null,
      materialName: item.materialName,
      thickness: item.thickness,
      sheetWidth: item.sheetWidth,
      sheetHeight: item.sheetHeight,
      profileType: item.profileType ?? null,
      profileLength: item.profileLength,
      profileDimensions: item.profileDimensions,
      baseMaterialPrice: item.baseMaterialPrice,
      isManualPrice: item.isManualPrice,
      isFullMaterial: item.isFullMaterial,
      materialCalcMode: item.materialCalcMode,
      sheetCount: item.sheetCount,
      hasPartialLastSheet: item.hasPartialLastSheet,
      partialSheetWidth: item.partialSheetWidth,
      partialSheetHeight: item.partialSheetHeight,
      chargeFullLastSheet: item.chargeFullLastSheet,
      computedSheetUnits: item.computedSheetUnits,
      profileBarCount: item.profileBarCount,
      hasPartialLastProfileBar: item.hasPartialLastProfileBar,
      partialProfileLength: item.partialProfileLength,
      chargeFullLastProfileBar: item.chargeFullLastProfileBar,
      computedProfileBarUnits: item.computedProfileBarUnits,
      scrapNotes: item.scrapNotes,
      isMaterialProvidedByClient: item.isMaterialProvidedByClient,
      cuttingGasId: item.cuttingGasId.toString(),
      cuttingTimeMinutes: item.cuttingTimeMinutes,
      chargeMinimumCutting: item.chargeMinimumCutting,
      cutWidth: item.cutWidth,
      cutHeight: item.cutHeight,
      cutLength: item.cutLength,
      usagePercentage: item.usagePercentage,
      setupRateId: item.setupRateId?.toString() ?? null,
      setupTimeMinutes: item.setupTimeMinutes,
      setupPricePerHour: item.setupPricePerHour,
      finishingDescription: item.finishingDescription,
      finishingPrice: item.finishingPrice,
      materialCost: item.materialCost,
      cuttingCost: item.cuttingCost,
      setupCost: item.setupCost,
      servicesCost: item.servicesCost,
      subtotalItemCost: item.subtotalItemCost,
      discountType: item.discountType ?? null,
      discountValue: item.discountValue,
      discountAmount: item.discountAmount,
      totalItemCost: item.totalItemCost,
      createdAt: item.createdAt,
    }
  }
}
